language: go
go:
  - 1.15.x
  - 1.16.x
  - 1.17.x

notifications:
  email: false

install:
  - export config=./conf.ini
  - go mod download

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS skeleton DEFAULT CHARACTER SET utf8mb4;'